version: '2'
services:
  rabbitmq:
    image: thethingsnetwork/rabbitmq
    hostname: rabbitserver
    environment:
      - RABBITMQ_SSL_CERTFILE=/var/lib/rabbitmq/tls/server.cert
      - RABBITMQ_SSL_KEYFILE=/var/lib/rabbitmq/tls/server.key
      - RABBITMQ_SSL_CACERTFILE=/var/lib/rabbitmq/tls/ca.cert
    ports:
      - "1883:1883"
      - "8883:8883"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
    volumes:
      - "./.env/mqtt:/var/lib/rabbitmq/tls"
      - "/var/lib/rabbitmq"
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "./.env/redis:/data"
  handler:
    image: thethingsnetwork/ttn
    hostname: handler
    working_dir: /root
    command: handler --config ./.env/handler/dev.yml
    depends_on:
      - rabbitmq
      - redis
    environment:
      - TERM
      - TTN_HANDLER_SERVER_ADDRESS_ANNOUNCE=handler.local.thethings.network
      - TTN_HANDLER_REDIS_ADDRESS=redis:6379
      - TTN_HANDLER_MQTT_ADDRESS=rabbitmq:1883
      - TTN_HANDLER_AMQP_ADDRESS=rabbitmq:5672
    ports:
      - "1904:1904"
      - "8084:8084"
    volumes:
      - "./.env/:/root/.env/"
